name: 'farmiq_data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'farmiq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  farmiq_data_pipeline:
    # Materialized views for performance
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      finance:
        +materialized: table
      operations:
        +materialized: table
      analytics:
        +materialized: table

tests:
  +schema: tests
  +data: tests

snapshots:
  farmiq_data_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
