farmiq:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_number }}"
      user: "{{ env_var('DB_USER', 'farmiq') }}"
      pass: "{{ env_var('DB_PASSWORD', 'farmiq_password') }}"
      dbname: "{{ env_var('DB_NAME', 'farmiq_analytics') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: "{{ env_var('DBT_THREADS', '4') | as_number }}"
      keepalives_idle: 0
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_number }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME', 'farmiq_analytics') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: "{{ env_var('DBT_THREADS', '8') | as_number }}"
      keepalives_idle: 0
  target: dev
