from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass
from typing import Any, Protocol

from app.schemas import AnalyzeRequest


@dataclass
class ProviderRunMeta:
    token_in: int | None = None
    token_out: int | None = None
    provider_latency_ms: int | None = None


class LlmProvider(Protocol):
    async def analyze(self, request: AnalyzeRequest) -> tuple[dict[str, Any], ProviderRunMeta]: ...


class MockProvider:
    def __init__(self, *, provider_name: str, model_name: str, prompt_version: str):
        self._provider_name = provider_name
        self._model_name = model_name
        self._prompt_version = prompt_version

    async def analyze(self, request: AnalyzeRequest) -> tuple[dict[str, Any], ProviderRunMeta]:
        payload = request.model_dump(mode="json")
        token_in = max(1, len(json.dumps(payload)) // 4)

        fcr = None
        for kpi in request.features.kpis:
            if kpi.code.upper() == "FCR":
                fcr = kpi
                break

        anomaly_count = len(request.features.anomalies)
        summary_parts: list[str] = []
        if fcr:
            summary_parts.append(f"FCR is {fcr.value:.2f}.")
            if fcr.delta24h is not None:
                delta = fcr.delta24h
                direction = "increased" if delta > 0 else "decreased"
                summary_parts.append(f"FCR {direction} by {abs(delta):.2f} vs prior 24h.")
        if anomaly_count:
            summary_parts.append(f"{anomaly_count} anomaly(ies) detected in the selected window.")

        summary = " ".join(summary_parts) if summary_parts else "No significant deviations detected in the selected window."
        confidence = 0.68 if anomaly_count or fcr else 0.55

        should_notify = bool(anomaly_count) or (request.mode in ("anomaly_explain", "action_recommendation"))
        severity: str = "info"
        if anomaly_count:
            sev_set = {a.severity for a in request.features.anomalies}
            severity = "critical" if "critical" in sev_set else "warning"

        insight: dict[str, Any] = {
            "summary": summary,
            "keyFindings": [
                {
                    "title": "Deterministic mock insight",
                    "detail": "This insight is generated by the mock provider for MVP and testing.",
                    "impact": "low",
                    "references": [],
                }
            ],
            "likelyCauses": [],
            "recommendedActions": [],
            "confidence": confidence,
            "references": [],
            "modelMeta": {
                "provider": self._provider_name,
                "model": self._model_name,
                "promptVersion": self._prompt_version,
            },
            "notificationHint": {
                "shouldNotify": should_notify,
                "severity": severity,
                "title": "New insight available",
                "message": "An insight was generated for your selected barn and time window.",
            },
        }

        token_out = max(1, len(json.dumps(insight)) // 4)
        return insight, ProviderRunMeta(token_in=token_in, token_out=token_out)


async def call_with_timeout(
    provider: LlmProvider, *, request: AnalyzeRequest, timeout_s: float
) -> tuple[dict[str, Any], ProviderRunMeta]:
    return await asyncio.wait_for(provider.analyze(request), timeout=timeout_s)
