/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public-variable-frontend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public variables for frontend */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public variables */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicVariableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard overview */
        get: {
            parameters: {
                query?: {
                    /** @description Tenant context. Resolved from JWT tenant_id claim when present; optional for platform_admin or dev mode. */
                    tenantId?: components["parameters"]["tenantId"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverviewResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Downstream error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/farms/{farmId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get farm dashboard */
        get: {
            parameters: {
                query?: {
                    /** @description Tenant context. Resolved from JWT tenant_id claim when present; optional for platform_admin or dev mode. */
                    tenantId?: components["parameters"]["tenantId"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path: {
                    farmId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Farm dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FarmDashboardResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Downstream error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/barns/{barnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get barn dashboard */
        get: {
            parameters: {
                query?: {
                    /** @description Tenant context. Resolved from JWT tenant_id claim when present; optional for platform_admin or dev mode. */
                    tenantId?: components["parameters"]["tenantId"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path: {
                    barnId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Barn dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarnDashboardResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Downstream error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get alerts for current tenant */
        get: {
            parameters: {
                query?: {
                    /** @description Tenant context. Resolved from JWT tenant_id claim when present; optional for platform_admin or dev mode. */
                    tenantId?: components["parameters"]["tenantId"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alerts data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Downstream error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get effective config context */
        get: {
            parameters: {
                query: {
                    /** @description Tenant context; required if not present in JWT claims. */
                    tenant_id: components["parameters"]["tenantIdSnake"];
                    farm_id?: components["parameters"]["farmIdSnake"];
                    barn_id?: components["parameters"]["barnIdSnake"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Config context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigContextResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threshold rules */
        get: {
            parameters: {
                query: {
                    /** @description Tenant context; required if not present in JWT claims. */
                    tenant_id: components["parameters"]["tenantIdSnake"];
                    farm_id?: components["parameters"]["farmIdSnake"];
                    barn_id?: components["parameters"]["barnIdSnake"];
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Threshold rules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThresholdsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Upsert threshold rule */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThresholdUpsertRequest"];
                };
            };
            responses: {
                /** @description Upsert result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThresholdUpsertResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List target curves */
        get: {
            parameters: {
                query: {
                    /** @description Tenant context; required if not present in JWT claims. */
                    tenant_id: components["parameters"]["tenantIdSnake"];
                    farm_id?: components["parameters"]["farmIdSnake"];
                    barn_id?: components["parameters"]["barnIdSnake"];
                    species?: string;
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Target curves */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TargetsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Upsert target curve */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TargetUpsertRequest"];
                };
            };
            responses: {
                /** @description Upsert result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TargetUpsertResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query audit events */
        get: {
            parameters: {
                query: {
                    /** @description Tenant context; required if not present in JWT claims. */
                    tenant_id: components["parameters"]["tenantIdSnake"];
                    actor?: string;
                    action?: string;
                    resource_type?: string;
                    from?: string;
                    to?: string;
                    page?: number;
                    limit?: number;
                };
                header: {
                    /** @description Request correlation ID. */
                    "x-request-id": components["parameters"]["xRequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEventsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: Record<string, never>;
                requestId?: string;
                /** Format: date-time */
                timestamp?: string;
                traceId?: string;
            };
        };
        PublicVariableResponse: {
            datadog_rum_env?: string | null;
        };
        OverviewResponse: {
            topology?: Record<string, never> | null;
            telemetry?: {
                metrics?: Record<string, never>;
                aggregates?: Record<string, never>[];
            };
            alerts?: Record<string, never>[];
            analyticsAvailable?: boolean;
        };
        FarmDashboardResponse: {
            farm?: Record<string, never> | null;
            barns?: Record<string, never>[];
            telemetryAggregates?: Record<string, never>[];
        };
        BarnDashboardResponse: {
            barn?: Record<string, never> | null;
            telemetryAggregates?: Record<string, never>[];
            telemetryReadings?: Record<string, never>[];
        };
        AlertsResponse: {
            alerts?: Record<string, never>[];
            analyticsAvailable?: boolean;
        };
        ConfigContextResponse: {
            data?: {
                [key: string]: unknown;
            };
        };
        ThresholdRule: {
            id?: string;
            tenant_id?: string;
            farm_id?: string | null;
            barn_id?: string | null;
            metric?: string;
            op?: string;
            value?: number;
            duration_sec?: number | null;
            severity?: string;
            enabled?: boolean;
        };
        ThresholdsResponse: {
            data?: components["schemas"]["ThresholdRule"][];
        };
        ThresholdUpsertRequest: {
            tenant_id: string;
            farm_id?: string | null;
            barn_id?: string | null;
            metric: string;
            op: string;
            value: number;
            severity?: string;
            enabled?: boolean;
            duration_sec?: number | null;
        };
        ThresholdUpsertResponse: {
            data?: {
                [key: string]: unknown;
            };
        };
        TargetCurve: {
            id?: string;
            tenant_id?: string;
            farm_id?: string | null;
            barn_id?: string | null;
            species?: string;
            day?: number;
            target_weight?: number;
            target_fcr?: number;
        };
        TargetsResponse: {
            data?: components["schemas"]["TargetCurve"][];
        };
        TargetUpsertRequest: {
            tenant_id: string;
            farm_id?: string | null;
            barn_id?: string | null;
            species: string;
            day: number;
            target_weight?: number;
            target_fcr?: number;
        };
        TargetUpsertResponse: {
            data?: {
                [key: string]: unknown;
            };
        };
        AuditEventsResponse: {
            data?: {
                [key: string]: unknown;
            }[];
            meta?: {
                page?: number;
                limit?: number;
                total?: number;
                hasNext?: boolean;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Request correlation ID. */
        xRequestId: string;
        /** @description Tenant context. Resolved from JWT tenant_id claim when present; optional for platform_admin or dev mode. */
        tenantId: string;
        /** @description Tenant context; required if not present in JWT claims. */
        tenantIdSnake: string;
        farmIdSnake: string;
        barnIdSnake: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
