openapi: 3.0.0
info:
  title: FarmIQ Cloud BFF Contract
  version: 1.0.0
  description: Contract-first API for dashboard-web (BFF only).
servers:
  - url: /
tags:
  - name: Auth
  - name: Users
  - name: Dashboard
  - name: Farms
  - name: Barns
  - name: Devices
  - name: Telemetry
  - name: WeighVision
  - name: Media

paths:
  /api/v1/auth/login:
    post:
      tags: [Auth]
      summary: Login
      operationId: authLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Tokens issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
        '401':
          description: Unauthorized

  /api/v1/auth/refresh:
    post:
      tags: [Auth]
      summary: Refresh tokens
      operationId: authRefresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Tokens refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
        '401':
          description: Unauthorized

  /api/v1/users/me:
    get:
      tags: [Users]
      summary: Get current user
      operationId: usersMe
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /api/v1/dashboard/overview:
    get:
      tags: [Dashboard]
      summary: Tenant dashboard overview
      operationId: dashboardOverview
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Overview data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardOverview'

  /api/v1/dashboard/alerts:
    get:
      tags: [Dashboard]
      summary: Dashboard alerts
      operationId: dashboardAlerts
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        '200':
          description: Alerts list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedAlerts'

  /api/v1/farms:
    get:
      tags: [Farms]
      summary: List farms
      operationId: farmsList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/query'
      responses:
        '200':
          description: Farm list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedFarms'

  /api/v1/farms/{farmId}:
    get:
      tags: [Farms]
      summary: Get farm detail
      operationId: farmsGet
      security:
        - bearerAuth: []
      parameters:
        - name: farmId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Farm detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Farm'

  /api/v1/barns:
    get:
      tags: [Barns]
      summary: List barns
      operationId: barnsList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/query'
      responses:
        '200':
          description: Barn list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedBarns'

  /api/v1/barns/{barnId}:
    get:
      tags: [Barns]
      summary: Get barn detail
      operationId: barnsGet
      security:
        - bearerAuth: []
      parameters:
        - name: barnId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Barn detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barn'

  /api/v1/devices:
    get:
      tags: [Devices]
      summary: List devices
      operationId: devicesList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/query'
      responses:
        '200':
          description: Device list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedDevices'

  /api/v1/devices/{deviceId}:
    get:
      tags: [Devices]
      summary: Get device detail
      operationId: devicesGet
      security:
        - bearerAuth: []
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Device detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'

  /api/v1/telemetry/readings:
    get:
      tags: [Telemetry]
      summary: List telemetry readings
      operationId: telemetryReadingsList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        '200':
          description: Telemetry readings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedTelemetryReadings'

  /api/v1/telemetry/aggregates:
    get:
      tags: [Telemetry]
      summary: List telemetry aggregates
      operationId: telemetryAggregatesList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        '200':
          description: Telemetry aggregates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedTelemetryAggregates'

  /api/v1/weighvision/sessions:
    get:
      tags: [WeighVision]
      summary: List weighvision sessions
      operationId: weighvisionSessionsList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        '200':
          description: Sessions list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedWeighvisionSessions'

  /api/v1/weighvision/sessions/{sessionId}:
    get:
      tags: [WeighVision]
      summary: Get weighvision session detail
      operationId: weighvisionSessionsGet
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Session detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeighvisionSession'

  /api/v1/media/objects:
    get:
      tags: [Media]
      summary: List media objects
      operationId: mediaObjectsList
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortDir'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        '200':
          description: Media objects list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedMediaObjects'

  /api/v1/media/objects/{objectId}:
    get:
      tags: [Media]
      summary: Get media object detail
      operationId: mediaObjectsGet
      security:
        - bearerAuth: []
      parameters:
        - name: objectId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tenantId'
      responses:
        '200':
          description: Media object detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaObject'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    tenantId:
      name: tenantId
      in: query
      required: false
      schema:
        type: string
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 500
        default: 50
    sortBy:
      name: sort_by
      in: query
      required: false
      schema:
        type: string
    sortDir:
      name: sort_dir
      in: query
      required: false
      schema:
        type: string
        enum: [asc, desc]
        default: desc
    query:
      name: q
      in: query
      required: false
      schema:
        type: string
    startTime:
      name: start_time
      in: query
      required: false
      schema:
        type: string
        format: date-time
    endTime:
      name: end_time
      in: query
      required: false
      schema:
        type: string
        format: date-time

  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        code:
          type: string
        message:
          type: string
        traceId:
          type: string

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string

    RefreshRequest:
      type: object
      required: [refresh_token]
      properties:
        refresh_token:
          type: string

    AuthTokens:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer

    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        tenant_id:
          type: string
          nullable: true
        roles:
          type: array
          items:
            type: string

    PageMeta:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer

    PagedFarms:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Farm'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedBarns:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Barn'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedDevices:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Device'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedTelemetryReadings:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TelemetryReading'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedTelemetryAggregates:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TelemetryAggregate'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedWeighvisionSessions:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/WeighvisionSession'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedMediaObjects:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MediaObject'
        meta:
          $ref: '#/components/schemas/PageMeta'

    PagedAlerts:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Alert'
        meta:
          $ref: '#/components/schemas/PageMeta'

    Farm:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        name:
          type: string
        location:
          type: string
          nullable: true
        status:
          type: string

    Barn:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        farm_id:
          type: string
        name:
          type: string
        animal_type:
          type: string
          nullable: true
        status:
          type: string

    Device:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        farm_id:
          type: string
          nullable: true
        barn_id:
          type: string
          nullable: true
        device_type:
          type: string
        serial_no:
          type: string
          nullable: true
        status:
          type: string

    TelemetryReading:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        farm_id:
          type: string
          nullable: true
        barn_id:
          type: string
          nullable: true
        device_id:
          type: string
        metric:
          type: string
        value:
          type: number
        unit:
          type: string
          nullable: true
        occurred_at:
          type: string
          format: date-time

    TelemetryAggregate:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        device_id:
          type: string
        metric:
          type: string
        bucket_start:
          type: string
          format: date-time
        bucket_size:
          type: string
        avg_value:
          type: number
        min_value:
          type: number
        max_value:
          type: number
        count:
          type: integer

    WeighvisionSession:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        farm_id:
          type: string
        barn_id:
          type: string
        device_id:
          type: string
        station_id:
          type: string
        status:
          type: string
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
          nullable: true

    MediaObject:
      type: object
      properties:
        id:
          type: string
        tenant_id:
          type: string
        farm_id:
          type: string
        barn_id:
          type: string
        device_id:
          type: string
        path:
          type: string
        mime_type:
          type: string
          nullable: true
        size_bytes:
          type: integer
          nullable: true
        captured_at:
          type: string
          format: date-time

    Alert:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        severity:
          type: string
        message:
          type: string
        occurred_at:
          type: string
          format: date-time

    DashboardOverview:
      type: object
      properties:
        topology:
          type: object
          nullable: true
        telemetry:
          type: object
        alerts:
          type: array
          items:
            $ref: '#/components/schemas/Alert'
        analyticsAvailable:
          type: boolean
