/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accessible tenants */
        get: operations["tenantsList"];
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List farms */
        get: operations["farmsList"];
    };
    "/api/v1/farms/{farmId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get farm detail */
        get: operations["farmsGet"];
    };
    "/api/v1/barns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List barns */
        get: operations["barnsList"];
    };
    "/api/v1/barns/{barnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get barn detail */
        get: operations["barnsGet"];
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices */
        get: operations["devicesList"];
    };
    "/api/v1/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get device detail */
        get: operations["devicesGet"];
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard overview */
        get: operations["dashboardOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telemetry readings */
        get: operations["telemetryReadingsList"];
    };
    "/api/v1/telemetry/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telemetry aggregates */
        get: operations["telemetryAggregatesList"];
    };
    "/api/v1/telemetry/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest telemetry readings */
        get: operations["telemetryLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weighvision/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List weighvision sessions */
        get: operations["weighvisionSessionsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weighvision/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weighvision session detail */
        get: operations["weighvisionSessionsGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weighvision/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weighvision analytics */
        get: operations["weighvisionAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeding/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily feed intake */
        get: operations["feedingDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeding/fcr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** FCR metrics and forecast */
        get: operations["feedingFcr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List anomalies */
        get: operations["analyticsAnomaliesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/anomalies/{anomalyId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge anomaly */
        post: operations["analyticsAnomaliesAcknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recommendations */
        get: operations["analyticsRecommendationsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run scenario analysis */
        post: operations["analyticsScenarioRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts */
        get: operations["alertsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge alert */
        post: operations["alertsAcknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data quality metrics */
        get: operations["opsDataQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync status */
        get: operations["opsSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate report */
        post: operations["reportsGenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get report status */
        get: operations["reportsGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create export */
        post: operations["exportCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get export status */
        get: operations["exportGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) */
        get: operations["adminUsersList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log (admin) */
        get: operations["adminAuditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            code?: string;
            message?: string;
            details?: Record<string, never>;
            requestId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PageMeta: {
            page?: number;
            limit?: number;
            total?: number;
            hasNext?: boolean;
        };
        PagedTenants: {
            data?: components["schemas"]["Tenant"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedFarms: {
            data?: components["schemas"]["Farm"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedBarns: {
            data?: components["schemas"]["Barn"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedDevices: {
            data?: components["schemas"]["Device"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedTelemetryReadings: {
            data?: components["schemas"]["TelemetryReading"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedTelemetryAggregates: {
            data?: components["schemas"]["TelemetryAggregate"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedWeighvisionSessions: {
            data?: components["schemas"]["WeighvisionSession"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedAlerts: {
            data?: components["schemas"]["Alert"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedAnomalies: {
            data?: components["schemas"]["Anomaly"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedRecommendations: {
            data?: components["schemas"]["Recommendation"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedUsers: {
            data?: components["schemas"]["AdminUser"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PagedAuditLogs: {
            data?: components["schemas"]["AuditLog"][];
            meta?: components["schemas"]["PageMeta"];
        };
        Tenant: {
            tenant_id?: string;
            name?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Farm: {
            farm_id?: string;
            tenant_id?: string;
            name?: string;
            location?: string | null;
            barn_count?: number;
            device_count?: number;
            status?: string;
            /** Format: date-time */
            last_activity?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Barn: {
            barn_id?: string;
            tenant_id?: string;
            farm_id?: string;
            name?: string;
            type?: string;
            device_count?: number;
            current_temperature?: number;
            current_humidity?: number;
            status?: string;
            /** Format: date-time */
            last_activity?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Device: {
            device_id?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            name?: string;
            serial_number?: string;
            type?: string;
            status?: string;
            /** Format: date-time */
            last_seen?: string;
            uptime_percent_24h?: number;
            firmware_version?: string;
        };
        FarmDetailResponse: {
            data?: components["schemas"]["Farm"] & {
                barns?: components["schemas"]["BarnSummary"][];
            };
        };
        BarnDetailResponse: {
            data?: components["schemas"]["Barn"] & {
                devices?: components["schemas"]["DeviceSummary"][];
            };
        };
        DeviceDetailResponse: {
            data?: components["schemas"]["Device"] & {
                uptime_percent_7d?: number;
                uptime_percent_30d?: number;
                telemetry_count_today?: number;
                /** Format: date-time */
                created_at?: string;
            };
        };
        BarnSummary: {
            barn_id?: string;
            name?: string;
            device_count?: number;
        };
        DeviceSummary: {
            device_id?: string;
            name?: string;
            type?: string;
            status?: string;
            /** Format: date-time */
            last_seen?: string;
        };
        DashboardOverviewResponse: {
            data?: {
                kpis?: Record<string, never>;
                recent_alerts?: components["schemas"]["Alert"][];
                recent_activity?: components["schemas"]["RecentActivity"][];
                weight_trend?: components["schemas"]["WeightTrend"][];
                sensor_status?: Record<string, never>;
            };
        };
        RecentActivity: {
            type?: string;
            barn_id?: string;
            barn_name?: string;
            /** Format: date-time */
            occurred_at?: string;
        };
        WeightTrend: {
            date?: string;
            avg_weight_kg?: number;
        };
        TelemetryAggregate: {
            id?: string;
            tenant_id?: string;
            device_id?: string;
            metric?: string;
            /** Format: date-time */
            bucket_start?: string;
            bucket_size?: string;
            avg_value?: number;
            min_value?: number;
            max_value?: number;
            count?: number;
        };
        TelemetryReadingsResponse: {
            data?: {
                readings?: components["schemas"]["TelemetryReading"][];
                statistics?: Record<string, never>;
                coverage_percent?: number;
            };
        };
        TelemetryReading: {
            /** Format: date-time */
            timestamp?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            device_id?: string;
            metric_type?: string;
            metric_value?: number;
            unit?: string;
        };
        TelemetryLatestResponse: {
            data?: {
                sensors?: components["schemas"]["TelemetrySensor"][];
            };
        };
        TelemetrySensor: {
            device_id?: string;
            device_name?: string;
            metrics?: components["schemas"]["TelemetryMetric"][];
            mini_trend?: number[];
        };
        TelemetryMetric: {
            metric_type?: string;
            value?: number;
            unit?: string;
            status?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        WeighvisionSession: {
            session_id?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            station_id?: string;
            batch_id?: string;
            status?: string;
            /** Format: date-time */
            start_at?: string;
            /** Format: date-time */
            end_at?: string;
            initial_weight_kg?: number;
            final_weight_kg?: number;
            image_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        WeighvisionSessionDetailResponse: {
            data?: {
                session_id?: string;
                tenant_id?: string;
                farm_id?: string;
                barn_id?: string;
                station_id?: string;
                batch_id?: string;
                status?: string;
                /** Format: date-time */
                start_at?: string;
                /** Format: date-time */
                end_at?: string;
                initial_weight_kg?: number;
                final_weight_kg?: number;
                image_count?: number;
                predictions?: components["schemas"]["WeighvisionPrediction"][];
                statistics?: Record<string, never>;
                images?: components["schemas"]["WeighvisionImage"][];
            };
        };
        WeighvisionPrediction: {
            image_id?: string;
            /** Format: date-time */
            timestamp?: string;
            predicted_weight_kg?: number;
            confidence_score?: number;
            size_proxy?: string;
            is_outlier?: boolean;
        };
        WeighvisionImage: {
            image_id?: string;
            presigned_url?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        WeighvisionAnalyticsResponse: {
            data?: {
                weight_trend?: components["schemas"]["WeighvisionTrendPoint"][];
                statistics?: Record<string, never>;
                distribution?: Record<string, never>;
            };
        };
        WeighvisionTrendPoint: {
            date?: string;
            avg_weight_kg?: number;
            min_weight_kg?: number;
            max_weight_kg?: number;
            p10_weight_kg?: number;
            p25_weight_kg?: number;
            p50_weight_kg?: number;
            p75_weight_kg?: number;
            p90_weight_kg?: number;
        };
        FeedingDailyResponse: {
            data?: {
                daily_feed?: components["schemas"]["FeedingDailyPoint"][];
                statistics?: Record<string, never>;
            };
        };
        FeedingDailyPoint: {
            date?: string;
            feed_intake_kg?: number;
            planned_feed_kg?: number;
            difference_kg?: number;
            cumulative_feed_kg?: number;
        };
        FeedingFcrResponse: {
            data?: {
                fcr_trend?: components["schemas"]["FcrPoint"][];
                current_metrics?: Record<string, never>;
                forecast?: Record<string, never>;
            };
        };
        FcrPoint: {
            date?: string;
            fcr?: number;
            adg_kg_per_day?: number;
            feed_intake_kg?: number;
            weight_gain_kg?: number;
        };
        Anomaly: {
            anomaly_id?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            device_id?: string;
            type?: string;
            severity?: string;
            status?: string;
            message?: string;
            /** Format: date-time */
            occurred_at?: string;
            /** Format: date-time */
            acknowledged_at?: string;
            acknowledged_by?: string;
            /** Format: date-time */
            resolved_at?: string;
        };
        AcknowledgeRequest: {
            notes?: string;
        };
        AcknowledgeResponse: {
            data?: {
                anomaly_id?: string;
                alert_id?: string;
                status?: string;
                /** Format: date-time */
                acknowledged_at?: string;
                acknowledged_by?: string;
            };
        };
        Recommendation: {
            recommendation_id?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            title?: string;
            category?: string;
            priority?: string;
            status?: string;
            description?: string;
            reasoning?: string;
            expected_impact?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ScenarioRequest: {
            context?: {
                farm_id?: string;
                barn_id?: string;
                batch_id?: string;
            };
            scenario_type?: string;
            parameters?: Record<string, never>;
            target_weight_kg?: number;
        };
        ScenarioResponse: {
            data?: {
                scenario_id?: string;
                baseline?: Record<string, never>;
                scenario?: Record<string, never>;
                impact?: Record<string, never>;
                confidence_score?: number;
                /** Format: date-time */
                computed_at?: string;
            };
        };
        Alert: {
            alert_id?: string;
            tenant_id?: string;
            farm_id?: string;
            barn_id?: string;
            device_id?: string;
            severity?: string;
            type?: string;
            status?: string;
            message?: string;
            /** Format: date-time */
            occurred_at?: string;
            /** Format: date-time */
            acknowledged_at?: string;
            acknowledged_by?: string;
            /** Format: date-time */
            resolved_at?: string;
        };
        OpsDataQualityResponse: {
            data?: {
                coverage_percent?: number;
                missing_data_periods?: components["schemas"]["MissingPeriod"][];
                device_uptime?: components["schemas"]["DeviceUptime"][];
                data_freshness?: Record<string, never>;
            };
        };
        MissingPeriod: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            duration_minutes?: number;
        };
        DeviceUptime: {
            device_id?: string;
            device_name?: string;
            uptime_percent_24h?: number;
            uptime_percent_7d?: number;
            uptime_percent_30d?: number;
            /** Format: date-time */
            last_seen?: string;
        };
        OpsSyncStatusResponse: {
            data?: {
                sync_backlog?: Record<string, never>;
                edge_clusters?: components["schemas"]["EdgeClusterSync"][];
                ingestion_errors_24h?: number;
                api_latency_p95_ms?: number;
            };
        };
        EdgeClusterSync: {
            cluster_id?: string;
            tenant_id?: string;
            status?: string;
            /** Format: date-time */
            last_sync?: string;
            sync_success_rate_24h?: number;
            pending_events?: number;
        };
        ReportGenerateRequest: {
            report_type?: string;
            context?: Record<string, never>;
            time_range?: components["schemas"]["TimeRange"];
            format?: string;
        };
        ReportGenerateResponse: {
            data?: {
                report_id?: string;
                status?: string;
                estimated_completion_seconds?: number;
                download_url?: string | null;
            };
        };
        ReportStatusResponse: {
            data?: {
                report_id?: string;
                status?: string;
                download_url?: string;
                /** Format: date-time */
                expires_at?: string;
                /** Format: date-time */
                created_at?: string;
            };
        };
        ExportCreateRequest: {
            data_type?: string;
            context?: Record<string, never>;
            time_range?: components["schemas"]["TimeRange"];
            filters?: Record<string, never>;
            format?: string;
            columns?: string[];
        };
        ExportCreateResponse: {
            data?: {
                export_id?: string;
                status?: string;
                estimated_completion_seconds?: number;
                download_url?: string | null;
            };
        };
        ExportStatusResponse: {
            data?: {
                export_id?: string;
                status?: string;
                download_url?: string;
                /** Format: date-time */
                expires_at?: string;
                /** Format: date-time */
                created_at?: string;
                file_size_bytes?: number;
            };
        };
        AdminUser: {
            user_id?: string;
            email?: string;
            name?: string;
            roles?: string[];
            status?: string;
            /** Format: date-time */
            last_login?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AuditLog: {
            audit_id?: string;
            /** Format: date-time */
            timestamp?: string;
            user_id?: string;
            user_email?: string;
            event_type?: string;
            resource_type?: string;
            resource_id?: string;
            resource_name?: string;
            action_details?: Record<string, never>;
            ip_address?: string;
        };
        TimeRange: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
        };
    };
    responses: never;
    parameters: {
        xRequestId: string;
        tenantIdRequired: string;
        tenantId: string;
        farmId: string;
        barnId: string;
        barnIdRequired: string;
        deviceId: string;
        stationId: string;
        batchId: string;
        page: number;
        limit: number;
        limitTelemetry: number;
        query: string;
        status: string;
        deviceType: string;
        deviceStatus: string;
        severity: string;
        type: string;
        priority: string;
        category: string;
        metricType: string;
        startTime: string;
        endTime: string;
        startTimeRequired: string;
        endTimeRequired: string;
        startDate: string;
        endDate: string;
        startDateRequired: string;
        endDateRequired: string;
        aggregation: string;
        groupBy: string;
        timeRange: "24h" | "7d" | "30d";
        eventType: string;
        userId: string;
        resourceType: string;
        role: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tenantsList: {
        parameters: {
            query?: never;
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenants list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTenants"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    farmsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
                q?: components["parameters"]["query"];
                status?: components["parameters"]["status"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farms list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedFarms"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    farmsGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                farmId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farm detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDetailResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    barnsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
                q?: components["parameters"]["query"];
                status?: components["parameters"]["status"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Barns list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedBarns"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    barnsGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                barnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Barn detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarnDetailResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    devicesList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_type?: components["parameters"]["deviceType"];
                status?: components["parameters"]["deviceStatus"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
                q?: components["parameters"]["query"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDevices"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    devicesGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetailResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dashboardOverview: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                time_range?: components["parameters"]["timeRange"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telemetryReadingsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_id?: components["parameters"]["deviceId"];
                metric_type?: components["parameters"]["metricType"];
                start_time: components["parameters"]["startTimeRequired"];
                end_time: components["parameters"]["endTimeRequired"];
                aggregation?: components["parameters"]["aggregation"];
                group_by?: components["parameters"]["groupBy"];
                limit?: components["parameters"]["limitTelemetry"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry readings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryReadingsResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telemetryAggregatesList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_id?: components["parameters"]["deviceId"];
                metric_type?: components["parameters"]["metricType"];
                start_time: components["parameters"]["startTimeRequired"];
                end_time: components["parameters"]["endTimeRequired"];
                aggregation?: components["parameters"]["aggregation"];
                group_by?: components["parameters"]["groupBy"];
                limit?: components["parameters"]["limit"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTelemetryAggregates"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telemetryLatest: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                barn_id: components["parameters"]["barnIdRequired"];
                device_type?: components["parameters"]["deviceType"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest telemetry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryLatestResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    weighvisionSessionsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                station_id?: components["parameters"]["stationId"];
                batch_id?: components["parameters"]["batchId"];
                status?: components["parameters"]["status"];
                start_date?: components["parameters"]["startDate"];
                end_date?: components["parameters"]["endDate"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedWeighvisionSessions"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    weighvisionSessionsGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                include_images?: boolean;
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeighvisionSessionDetailResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    weighvisionAnalytics: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                batch_id?: components["parameters"]["batchId"];
                start_date: components["parameters"]["startDateRequired"];
                end_date: components["parameters"]["endDateRequired"];
                aggregation?: components["parameters"]["aggregation"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeighvisionAnalyticsResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedingDaily: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                batch_id?: components["parameters"]["batchId"];
                start_date: components["parameters"]["startDateRequired"];
                end_date: components["parameters"]["endDateRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily feed data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingDailyResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedingFcr: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                batch_id?: components["parameters"]["batchId"];
                start_date: components["parameters"]["startDateRequired"];
                end_date: components["parameters"]["endDateRequired"];
                target_weight_kg?: number;
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FCR response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingFcrResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyticsAnomaliesList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_id?: components["parameters"]["deviceId"];
                severity?: components["parameters"]["severity"];
                status?: components["parameters"]["status"];
                type?: components["parameters"]["type"];
                start_time?: components["parameters"]["startTime"];
                end_time?: components["parameters"]["endTime"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anomalies list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAnomalies"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyticsAnomaliesAcknowledge: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                anomalyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeRequest"];
            };
        };
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyticsRecommendationsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                priority?: components["parameters"]["priority"];
                status?: components["parameters"]["status"];
                category?: components["parameters"]["category"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendations list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedRecommendations"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyticsScenarioRun: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Scenario result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    alertsList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_id?: components["parameters"]["deviceId"];
                severity?: components["parameters"]["severity"];
                status?: components["parameters"]["status"];
                type?: components["parameters"]["type"];
                start_time?: components["parameters"]["startTime"];
                end_time?: components["parameters"]["endTime"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alerts list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAlerts"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    alertsAcknowledge: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeRequest"];
            };
        };
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    opsDataQuality: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                farm_id?: components["parameters"]["farmId"];
                barn_id?: components["parameters"]["barnId"];
                device_id?: components["parameters"]["deviceId"];
                start_time: components["parameters"]["startTimeRequired"];
                end_time: components["parameters"]["endTimeRequired"];
                metric_type?: components["parameters"]["metricType"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data quality */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsDataQualityResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    opsSyncStatus: {
        parameters: {
            query?: {
                tenantId?: components["parameters"]["tenantId"];
                edge_cluster_id?: string;
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsSyncStatusResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reportsGenerate: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportGenerateRequest"];
            };
        };
        responses: {
            /** @description Report generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportGenerateResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reportsGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatusResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportCreate: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreateRequest"];
            };
        };
        responses: {
            /** @description Export created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportCreateResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportGet: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path: {
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportStatusResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUsersList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                role?: components["parameters"]["role"];
                status?: components["parameters"]["status"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
                q?: components["parameters"]["query"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedUsers"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminAuditList: {
        parameters: {
            query: {
                tenantId: components["parameters"]["tenantIdRequired"];
                event_type?: components["parameters"]["eventType"];
                user_id?: components["parameters"]["userId"];
                resource_type?: components["parameters"]["resourceType"];
                start_time: components["parameters"]["startTimeRequired"];
                end_time: components["parameters"]["endTimeRequired"];
                page?: components["parameters"]["page"];
                limit?: components["parameters"]["limit"];
                q?: components["parameters"]["query"];
            };
            header: {
                "x-request-id": components["parameters"]["xRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAuditLogs"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
