apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-api-gateway-bff-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/farmiq/farmiq-manifests
    targetRevision: main
    path: helm/cloud-api-gateway-bff
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: farmiq-cloud-prod
  syncPolicy:
    # Manual sync for production
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
