apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-api-gateway-bff-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/farmiq/farmiq-manifests
    targetRevision: staging
    path: helm/cloud-api-gateway-bff
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: farmiq-cloud-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
