import React, { useEffect, useState } from 'react';
import { 
  Box,
  Grid, 
  Typography, 
  Stack, 
  alpha, 
  useTheme, 
  Button, 
  LinearProgress,
  Chip
} from '@mui/material';
import { 
  Brain, 
  Zap, 
  TrendingUp, 
  AlertTriangle, 
  ChevronRight,
  Sparkles
} from 'lucide-react';
import { PageHeader } from '../../../components/layout/PageHeader';
import { EmptyState } from '../../../components/EmptyState';
import { ErrorState } from '../../../components/feedback/ErrorState';
import { LoadingCard } from '../../../components/LoadingCard';
import { PremiumCard } from '../../../components/common/PremiumCard';
import { api } from '../../../api';
import { useActiveContext } from '../../../contexts/ActiveContext';
import type { components } from '@farmiq/api-client';

type Recommendation = components['schemas']['Recommendation'];

export const RecommendationsPage: React.FC = () => {
  const theme = useTheme();
  const { tenantId, farmId, barnId } = useActiveContext();
  const [items, setItems] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  // Temporary Mock Data
  const MOCK_RECOMMENDATIONS: Recommendation[] = [
    {
      recommendation_id: '1',
      title: 'Optimize Fan Speed in Barn 2',
      description: 'Humidity levels are rising. increasing fan speed by 15% will stabilize the environment.',
      category: 'environment',
      confidence: 0.92,
      impact: 'high',
      status: 'new',
      created_at: new Date().toISOString()
    },
    {
      recommendation_id: '2',
      title: 'Adjust Feed Mix Ratio',
      description: 'Protein intake is slightly below target. Adjust soybean meal ratio to 22% for the next batch.',
      category: 'feeding',
      confidence: 0.85,
      impact: 'medium',
      status: 'new',
      created_at: new Date().toISOString()
    },
    {
      recommendation_id: '3',
      title: 'Schedule Preventive Maintenance',
      description: 'Sensor #402 is showing erratic behavior implying potential calibration drift.',
      category: 'health',
      confidence: 0.78,
      impact: 'low',
      status: 'new',
      created_at: new Date().toISOString()
    }
  ];

  useEffect(() => {
    const fetchRecommendations = async () => {
      // Simulate API call
      setLoading(true);
      setTimeout(() => {
         setItems(MOCK_RECOMMENDATIONS);
         setLoading(false);
         setError(null);
      }, 800);
    };

    fetchRecommendations();
  }, [tenantId, farmId, barnId]);

  const getCategoryIcon = (category?: string) => {
    switch (category?.toLowerCase()) {
      case 'environment': return <Zap size={20} />;
      case 'feeding': return <TrendingUp size={20} />;
      case 'health': return <AlertTriangle size={20} />;
      default: return <Brain size={20} />;
    }
  };

  const getCategoryColor = (category?: string | null) => {
    const cat = category?.toLowerCase();
    if (cat === 'environment') return theme.palette.info.main;
    if (cat === 'feeding') return theme.palette.success.main;
    if (cat === 'health') return theme.palette.error.main;
    return theme.palette.primary.main;
  };

  if (error) return <ErrorState title="AI Engine Desync" message={error.message} />;
  
  if (loading && items.length === 0) {
    return (
      <Box>
        <PageHeader title="AI Intelligence Hub" subtitle="Real-time operational optimization and predictive coaching" />
        <Grid container spacing={3} sx={{ mt: 1 }}>
            {[1, 2, 3].map(i => (
                <Grid item xs={12} md={4} key={i}>
                    <PremiumCard sx={{ height: 320 }}>
                        <LoadingCard title="Analyzing data patterns..." lines={4} />
                    </PremiumCard>
                </Grid>
            ))}
        </Grid>
      </Box>
    );
  }

  return (
    <Box sx={{ animation: 'fadeIn 0.6s ease-out' }}>
      <PageHeader 
        title="AI Intelligence Hub" 
        subtitle="Real-time operational optimization and predictive coaching generated by the FarmIQ Engine" 
        primaryAction={{
            label: 'Run Analysis',
            onClick: () => {},
            startIcon: <Sparkles size={18} />
        }}
      />
      
      {items.length === 0 ? (
        <EmptyState 
            icon={<Brain size={48} />}
            title="Collecting Patterns..." 
            description="The AI engine needs more historical data to generate meaningful recommendations for this context." 
        />
      ) : (
        <Grid container spacing={3} sx={{ mt: 1 }}>
          {items.map((item, index) => {
              const color = getCategoryColor((item as any).category);
              const confidence = (item as any).confidence || 0.75;
              return (
                <Grid item xs={12} md={4} key={item.recommendation_id || index}>
                  <PremiumCard 
                    hoverable
                    sx={{ 
                        height: '100%', 
                        display: 'flex', 
                        flexDirection: 'column',
                        animation: `fadeInUp 0.5s ease-out ${index * 0.1}s both`
                    }}
                  >
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 3 }}>
                        <Box sx={{ 
                            p: 1.5, 
                            borderRadius: 2, 
                            bgcolor: alpha(color, 0.1), 
                            color: color,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}>
                            {getCategoryIcon((item as any).category)}
                        </Box>
                        <Chip 
                            label={`${Math.round(confidence * 100)}% Confidence`}
                            size="small"
                            sx={{ 
                                fontWeight: 800, 
                                bgcolor: alpha(color, 0.05), 
                                color: color,
                                border: '1px solid',
                                borderColor: alpha(color, 0.2)
                            }}
                        />
                    </Box>

                    <Typography variant="h6" fontWeight="800" sx={{ mb: 1.5, lineHeight: 1.3 }}>
                        {item.title}
                    </Typography>
                    
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 4, flexGrow: 1, lineHeight: 1.6, fontWeight: 500 }}>
                        {item.description}
                    </Typography>

                    <Box sx={{ mt: 'auto' }}>
                        <Stack spacing={1.5} sx={{ mb: 3 }}>
                            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <Typography variant="caption" fontWeight="800" color="text.disabled" sx={{ textTransform: 'uppercase', letterSpacing: 1 }}>Engine Certainty</Typography>
                                <Typography variant="caption" fontWeight="800" color={color}>
                                    {Math.round(confidence * 100)}%
                                </Typography>
                            </Box>
                            <LinearProgress 
                                variant="determinate" 
                                value={confidence * 100} 
                                sx={{ 
                                    height: 8, 
                                    borderRadius: 4,
                                    bgcolor: alpha(color, 0.1),
                                    '& .MuiLinearProgress-bar': {
                                        bgcolor: color,
                                        borderRadius: 4
                                    }
                                }}
                            />
                        </Stack>

                        <Button 
                            fullWidth 
                            variant="contained" 
                            color="primary"
                            endIcon={<ChevronRight size={16} />}
                            sx={{ 
                                fontWeight: 800, 
                                py: 1.2, 
                                borderRadius: 2,
                                boxShadow: `0 8px 16px -4px ${alpha(theme.palette.primary.main, 0.3)}`
                            }}
                        >
                            Apply Optimization
                        </Button>
                    </Box>
                  </PremiumCard>
                </Grid>
              );
          })}
        </Grid>
      )}
    </Box>
  );
};
